[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# OpenZeppelin remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
base-sepolia = "https://sepolia.base.org"
base-mainnet = "https://mainnet.base.org"

[etherscan]
base-sepolia = { key = "", url = "https://sepolia.basescan.org" }
base-mainnet = { key = "", url = "https://basescan.org" }
