name: Deploy Cloudflare Workers

on:
  push:
    branches: [ main ]
    paths:
      - 'coinbase/fc-minikit/src/**'
      - 'coinbase/fc-minikit/wrangler.toml'
      - '.github/workflows/cloudflare-only.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Wrangler CLI
        run: npm install -g wrangler@latest
        
      - name: Deploy to Cloudflare Workers
        run: |
          cd coinbase/fc-minikit
          wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} 