name: Deploy Cloudflare Workers

on:
  push:
    branches: [ main ]

jobs:
  deploy-cloudflare:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Workers
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Wrangler CLI
        run: npm install -g wrangler@4.24.0
        
      - name: Deploy to Cloudflare Workers
        run: |
          cd coinbase/cloudflare-api
          WRANGLER_TELEMETRY_DISABLED=1 wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} 